<?php
/**
 * @category    Fishpig
 * @package     Fishpig_Wordpress
 * @license     http://fishpig.co.uk/license.txt
 * @author      Ben Tideswell <help@fishpig.co.uk>
 */
?>
<?php $post = $this->getPost() ?>
<div class="post-list-item">
	
	<?php echo $this->getBeforePostContentHtml() ?>

	<div class="post-entry entry<?php if ($post->getFeaturedImage()): ?> post-entry-with-image<?php endif; ?>">
		<?php if ($post->isViewableForVisitor()): ?>
			<?php if ($featuredImage = $post->getFeaturedImage()): ?>
				<div class="featured-image left">
					<img src="<?php echo $featuredImage->getFullSizeImage() ?>" alt="<?php echo $this->escapeHtml($post->getPostTitle()) ?>"/>
				</div>
			<?php endif; ?>
			<div class="post_list_right">
				<h2><a href="<?php echo $post->getPermalink() ?>" title="<?php echo $this->escapeHtml($post->getPostTitle()) ?>"><?php echo $this->escapeHtml($post->getPostTitle()) ?></a></h2>
					<span class="post-date when time">
						<i class="fa fa-calendar" aria-hidden="true"></i>
						<span class="day"><?php echo __('Data:') ?> <?php echo $post->getPostDate('d'); ?>/<?php echo $post->getPostDate('m'); ?>/<?php echo $post->getPostDate('y'); ?></span> 
					</span>
				<?php if ($this->displayExcerptInFeed() || $post->hasMoreTag()): ?>
					<?php 
						/**
						* You can pass the number of words you want the excerpt to be shortened to like so
						* The below code will only show the first 50 words of the excerpt
						* <?php echo $post->getPostExcerpt(50) ?>
						*
						**/ 
					?>
					<?php echo $post->getPostExcerpt(50) ?>

				<?php else: ?>
					<?php echo substr($post->getPostContent(), 0, 118) .((strlen($post->getPostContent()) > 118) ? '...' : ''); ?>
					<a href="<?php echo $post->getPermalink() ?>" class="scopri"><?php echo __('Scopri') ?></a>
				<?php endif; ?>
			</div>
		<?php else: ?>
			<?php echo $this->getPasswordProtectHtml($post) ?>
		<?php endif; ?>
	</div>
	<?php echo $this->getAfterPostContentHtml() ?>

</div>