<?php
$_order = Mage::registry('current_order');

if (!$_order) {
    return;
}

$fields = Mage::helper('checkoutfields')->getFields();

?>

<div id="checkoutfields">
    <div class="hor-scroll">
        <table cellspacing="0" class="form-list">
        <?php foreach ($fields as $field => $config) : ?>
            <?php $value = (string)$_order->getData($field) ?>

            <?php
            if (!strlen($value)) :
                continue;
            endif;
            ?>

            <tr>
                <td class="label">
                    <label><?php echo $this->escapeHtml($config['label']) ?></label>
                </td>
                <td class="value">
                    <?php echo $this->escapeHtml($value) ?>
                </td>
            </tr>
        <?php endforeach; ?>
        </table>
    </div>
</div>

<script type="text/javascript">
document.observe('dom:loaded', function() {
    var div = $('sales_order_view_tabs_order_info_content').down('.box-right').down('.fieldset');
    if (!div) {
        return;
    }
    div.insert({
        bottom: $('checkoutfields')
    });
});
</script>
