<div id="checkout-review" class="firecheckout-section">
    <?php $additional = trim($this->getChildHtml('checkout.additional.information')); ?>
<?php /*
    <?php if ($additional) : ?>
        <div class="block-title"><span><?php echo $this->__('Order Confirmation') ?></span></div>
        <?php echo $this->getChildHtml('checkout.additional.information'); ?>
        <div class="block-subtitle"><span><?php echo $this->__('Checkout Review') ?></span></div>
    <?php else : ?>
        <div class="block-title"><span><?php echo $this->__('RIEPILOGO ORDINE') ?></span></div>
    <?php endif ?>
*/ ?>
    <div class="block-title"><span><?php echo $this->__('RIEPILOGO ORDINE') ?></span></div>
    <?php $agreements = $this->getChildHtml('agreements') ?>
    <div id="agreements-wrapper" class="checkout-agreements-load">
        <?php echo $agreements; ?>
    </div>
    <div id="checkout-review-load">
        <?php echo $this->getChildHtml('info') ?>
    </div>
    <?php
    $html = $this->getChildHtml('review_after');
    if ($html || $blockId = Mage::getStoreConfig('firecheckout/additional_content/reviewtable_after')) : ?>
        <div class="firecheckout-items-after">
            <?php echo $blockId ? $this->getLayout()->createBlock('cms/block')->setBlockId($blockId)->toHtml() : ''; ?>
            <?php echo $html ?>
        </div>
    <?php endif; ?>
    <script type="text/javascript">
        //<![CDATA[
            review = new Review(); // dummy class for various payment methods
        //]]>
    </script>
    
    <div class="atelier-checkout-text">
        <?php echo $this->getChildHtml('checkout.additional.information'); ?>
        <div class="bottom-icon-shop">
            <span><strong><i class="fa fa-shopping-cart" aria-hidden="true"></i>Hai dimenticato un articolo? </strong><a href="<?php echo $this->getUrl('checkout/cart'); ?>"> Modifica il tuo carrello</a></span>
        </div>
        <div class="sulla-policy">
            <input class="required-entry" name="policy" type="checkbox">
            <label><?php echo __("Autorizzo il trattamento dei dati personali ai sensi dell'articolo 13 D.Lgs. 196/2003") ?></label>
        </div>
    </div>


</div>